//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int Id { get; set; }
        public string Kitap_adi { get; set; }
        public int Sayfa_Sayisi { get; set; }
        public Nullable<int> Cilt_No { get; set; }
        public string Turu { get; set; }
        public string Yazar { get; set; }
        public System.DateTime Basim_Tarihi { get; set; }
    }
}
